icbc:
  drvrLastName: ""
  licenceNumber: ""
  keyword: ""
  expactAfterDate: "2024-05-01" #YYYY-MM-DD
  expactBeforeDate: "2022-07-04" #YYYY-MM-DD
  expactAfterTime: "09:00" #HH:MM
  expactBeforeTime: "16:30" #HH:MM
  examClass: 5 #5/7
